/*
 * (C) Copyright 2010. Beceem Communications Inc. All rights reserved.
 * 
 * Disclaimer :
 *
 * EXCEPT AS SET FORTH IN BECEEM'S TERMS AND CONDITIONS OF SALE, BECEEM
 * ASSUMES NO LIABILITY WHATSOEVER AND DISCLAIMS ANY EXPRESS, IMPLIED OR
 * STATUTORY WARRANTY RELATING TO ITS PRODUCTS INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
 * PURPOSE, OR NON-INFRINGEMENT. IN NO EVENT SHALL BECEEM BE LIABLE FOR
 * ANY DIRECT, INDIRECT, CONSEQUENTIAL, PUNITIVE, SPECIAL OR INCIDENTAL
 * DAMAGES (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF PROFITS,
 * BUSINESS INTERRUPTION OR LOSS OF INFORMATION) ARISING OUT OF THE USE
 * OR INABILITY TO USE THIS DOCUMENT, EVEN IF BECEEM HAS BEEN ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGES. 
 * 
 * Trademarks :
 *
 * Beceem, Beceem Communications, and Mobilizing Broadband are registered
 * trademarks of Beceem Communications Inc.  The Beceem logo is a
 * trademark of Beceem Communications Inc.
 *
 * Description	:	OMA-DM node info offset calculator.
 * Author		:
 * Reviewer		:
 *
 */


#include "OMADMTreeStruct.h"
#include "OMADMUserApi.h"
#include "PrivateTypedefs.h"

#ifdef WIN32
	#pragma warning(disable : 4311)
#endif

OMA_DM_NODE_INFO g_OmaDmNodeInfo[52][13]=
{

/*size details for structure ST_ROOT */
	{
		{OMA_DM_ST_ROOT_U32VERSION,OFFSET_TO_FIELD(ST_ROOT,u32Version),0,sizeof(UINT32),0},
		{OMA_DM_ST_ROOT_U32STRUCT_SIZE,OFFSET_TO_FIELD(ST_ROOT,u32StructSize),0,sizeof(UINT32),0},
		{OMA_DM_ST_ROOT_DEV_INFO,OFFSET_TO_FIELD(ST_ROOT,DevInfo),0,sizeof(ST_DevInfo),0},
		{OMA_DM_ST_ROOT_DMACC,OFFSET_TO_FIELD(ST_ROOT,DMAcc),1,sizeof(ST_DMAcc),OMA_DM_TREE_DMACC_NUMBER_OF_NODE},
		{OMA_DM_ST_ROOT_DEV_DETAIL,OFFSET_TO_FIELD(ST_ROOT,DevDetail),0,sizeof(ST_DevDetail),0},
		{OMA_DM_ST_ROOT_WIMAX,OFFSET_TO_FIELD(ST_ROOT,WIMAX),0,sizeof(ST_WIMAX),0},
		{OMA_DM_ST_ROOT_WIMAXSUPP,OFFSET_TO_FIELD(ST_ROOT,WIMAXSupp),0,sizeof(ST_WIMAXSupp),0},
		{OMA_DM_ST_ROOT_IP,OFFSET_TO_FIELD(ST_ROOT,IP),0,sizeof(ST_IP),0},
		{OMA_DM_ST_ROOT_APPS,OFFSET_TO_FIELD(ST_ROOT,Apps),1,sizeof(ST_Apps),OMA_DM_TREE_APPS_NUMBER_OF_NODE},
		{OMA_DM_ST_ROOT_FUMO,OFFSET_TO_FIELD(ST_ROOT,FUMO),1,sizeof(ST_FUMO),OMA_DM_TREE_FUMO_NUMBER_OF_NODE},
		{OMA_DM_ST_ROOT_MRUDATA,OFFSET_TO_FIELD(ST_ROOT,MRUData),0,sizeof(ST_MRU_TABLE),0},
	},


/*size details for structure ST_DevInfo */
	{
		{OMA_DM_ST_DEV_INFO_DEV_ID,OFFSET_TO_FIELD(ST_DevInfo,DevId),1,sizeof(UINT8),DEVICE_ID_LEAF_SIZE},
		{OMA_DM_ST_DEV_INFO_MAN,OFFSET_TO_FIELD(ST_DevInfo,Man),1,sizeof(UINT8),MANUFATURER_NAME_LEAF_SIZE},
		{OMA_DM_ST_DEV_INFO_MOD,OFFSET_TO_FIELD(ST_DevInfo,Mod),1,sizeof(UINT8),MODEL_NUMBER_LEAF_SIZE},
		{OMA_DM_ST_DEV_INFO_DMV,OFFSET_TO_FIELD(ST_DevInfo,Dmv),1,sizeof(UINT8),OMA_DM_CLIENT_VERSION_LEAF_SIZE},
		{OMA_DM_ST_DEV_INFO_LANG,OFFSET_TO_FIELD(ST_DevInfo,Lang),1,sizeof(UINT8),LANGUAGE_LEAF_SIZE},
	},


/*size details for structure ST_DMAcc */
	{
		{OMA_DM_ST_DMACC_APP_ID,OFFSET_TO_FIELD(ST_DMAcc,AppID),1,sizeof(UINT8),DMACC_APPID_LEAF_SIZE},
		{OMA_DM_ST_DMACC_SERVER_ID,OFFSET_TO_FIELD(ST_DMAcc,ServerID),1,sizeof(UINT8),DMACC_SERVERID_LEAF_SIZE},
		{OMA_DM_ST_DMACC_NAME,OFFSET_TO_FIELD(ST_DMAcc,Name),1,sizeof(UINT8),DMACC_NAME_LEAF_SIZE},
		{OMA_DM_ST_DMACC_PREF_CON_REF,OFFSET_TO_FIELD(ST_DMAcc,PrefConRef),1,sizeof(UINT8),DMACC_PREFCONREF_LEAF_SIZE},
		{OMA_DM_ST_DMACC_TO_CON_REF,OFFSET_TO_FIELD(ST_DMAcc,ToConRef),1,sizeof(ST_ToConRef),DMACC_TOCONNECTIONREF_NUMBER_OF_NODES},
		{OMA_DM_ST_DMACC_APP_ADDR,OFFSET_TO_FIELD(ST_DMAcc,AppAddr),1,sizeof(ST_AppAddr),DMACC_APPADDR_NUMBER_OF_NODES},
		{OMA_DM_ST_DMACC_AAUTH_PREF,OFFSET_TO_FIELD(ST_DMAcc,AAuthPref),1,sizeof(UINT8),DMACC_AUTHPREF_LEAF_SIZE},
		{OMA_DM_ST_DMACC_APP_AUTH,OFFSET_TO_FIELD(ST_DMAcc,AppAuth),1,sizeof(ST_AppAuth),DMACC_APPAUTH_NUMBER_OF_NODES},
	},


/*size details for structure ST_ToConRef */
	{
		{OMA_DM_ST_TO_CON_REF_CON_REF,OFFSET_TO_FIELD(ST_ToConRef,ConRef),1,sizeof(UINT8),CONNECTION_REFERENCES_LEAF_SIZE},
	},


/*size details for structure ST_AppAddr */
	{
		{OMA_DM_ST_APP_ADDR_ADDR,OFFSET_TO_FIELD(ST_AppAddr,Addr),1,sizeof(UINT8),APP_ADDRESS_LEAF_SIZE},
		{OMA_DM_ST_APP_ADDR_ADDR_TYPE,OFFSET_TO_FIELD(ST_AppAddr,AddrType),1,sizeof(UINT8),APP_ADDRESS_TYPE_LEAF_SIZE},
		{OMA_DM_ST_APP_ADDR_PORT,OFFSET_TO_FIELD(ST_AppAddr,Port),1,sizeof(ST_Port),APP_PORT_NUMBER_OF_NODES},
	},


/*size details for structure ST_Port */
	{
		{OMA_DM_ST_PORT_PORT_NBR,OFFSET_TO_FIELD(ST_Port,PortNbr),1,sizeof(UINT8),PORT_NUMBER_LEAF_SIZE},
	},


/*size details for structure ST_AppAuth */
	{
		{OMA_DM_ST_APP_AUTH_AAUTH_LEVEL,OFFSET_TO_FIELD(ST_AppAuth,AAuthLevel),1,sizeof(UINT8),APP_AUTHLEVEL_LEAF_SIZE},
		{OMA_DM_ST_APP_AUTH_AAUTH_TYPE,OFFSET_TO_FIELD(ST_AppAuth,AAuthType),1,sizeof(UINT8),APP_AUTHTYPE_LEAF_SIZE},
		{OMA_DM_ST_APP_AUTH_AAUTH_NAME,OFFSET_TO_FIELD(ST_AppAuth,AAuthName),1,sizeof(UINT8),APP_AUTHNAME_LEAF_SIZE},
		{OMA_DM_ST_APP_AUTH_AAUTH_SECRET,OFFSET_TO_FIELD(ST_AppAuth,AAuthSecret),1,sizeof(UINT8),APP_AUTHSECRET_LEAF_SIZE},
		{OMA_DM_ST_APP_AUTH_AAUTH_DATA,OFFSET_TO_FIELD(ST_AppAuth,AAuthData),1,sizeof(UINT8),APP_AUTHDATA_LEAF_SIZE},
	},


/*size details for structure ST_DevDetail */
	{
		{OMA_DM_ST_DEV_DETAIL_URI,OFFSET_TO_FIELD(ST_DevDetail,URI),0,sizeof(ST_URI),0},
		{OMA_DM_ST_DEV_DETAIL_DEV_TYPE,OFFSET_TO_FIELD(ST_DevDetail,DevType),1,sizeof(UINT8),DEVDETAIL_DEVTYPE_LEAF_SIZE},
		{OMA_DM_ST_DEV_DETAIL_OEM,OFFSET_TO_FIELD(ST_DevDetail,OEM),1,sizeof(UINT8),DEVDETAIL_OEM_LEAF_SIZE},
		{OMA_DM_ST_DEV_DETAIL_FW_V,OFFSET_TO_FIELD(ST_DevDetail,FwV),1,sizeof(UINT8),DEVDETAIL_FWV_LEAF_SIZE},
		{OMA_DM_ST_DEV_DETAIL_SW_V,OFFSET_TO_FIELD(ST_DevDetail,SwV),1,sizeof(UINT8),DEVDETAIL_SWV_LEAF_SIZE},
		{OMA_DM_ST_DEV_DETAIL_HW_V,OFFSET_TO_FIELD(ST_DevDetail,HwV),1,sizeof(UINT8),DEVDETAIL_HWV_LEAF_SIZE},
		{OMA_DM_ST_DEV_DETAIL_LRG_OBJ,OFFSET_TO_FIELD(ST_DevDetail,LrgObj),0,sizeof(UINT32),0},
	},


/*size details for structure ST_URI */
	{
		{OMA_DM_ST_URI_MAX_DEPTH,OFFSET_TO_FIELD(ST_URI,MaxDepth),0,sizeof(UINT32),0},
		{OMA_DM_ST_URI_MAX_TOT_LEN,OFFSET_TO_FIELD(ST_URI,MaxTotLen),0,sizeof(UINT32),0},
		{OMA_DM_ST_URI_MAX_SEG_LEN,OFFSET_TO_FIELD(ST_URI,MaxSegLen),0,sizeof(UINT32),0},
	},


/*size details for structure ST_WIMAX */
	{
		{OMA_DM_ST_WIMAX_WIMAXRADIO_MODULE,OFFSET_TO_FIELD(ST_WIMAX,WIMAXRadioModule),1,sizeof(ST_WIMAXRadioModule),WIMAX_WIMAXRADIO_NUMBER_OF_NODES},
		{OMA_DM_ST_WIMAX_TERMINAL_EQUIPMENT,OFFSET_TO_FIELD(ST_WIMAX,TerminalEquipment),0,sizeof(ST_TerminalEquipment),0},
		{OMA_DM_ST_WIMAX_TO_WIMAX_REF,OFFSET_TO_FIELD(ST_WIMAX,TO_WIMAX_REF),1,sizeof(UINT8),WIMAX_WIMAX_REF_LEAF_SIZE},
		{OMA_DM_ST_WIMAX_DEV_CAP,OFFSET_TO_FIELD(ST_WIMAX,DevCap),0,sizeof(ST_DevCap),0},
	},


/*size details for structure ST_WIMAXRadioModule */
	{
		{OMA_DM_ST_WIMAXRADIO_MODULE_MAN,OFFSET_TO_FIELD(ST_WIMAXRadioModule,Man),1,sizeof(UINT8),WIMAXRADIO_MAN_LEAF_SIZE},
		{OMA_DM_ST_WIMAXRADIO_MODULE_MOD,OFFSET_TO_FIELD(ST_WIMAXRadioModule,Mod),1,sizeof(UINT8),WIMAXRADIO_MOD_LEAF_SIZE},
		{OMA_DM_ST_WIMAXRADIO_MODULE_FW_V,OFFSET_TO_FIELD(ST_WIMAXRadioModule,FwV),1,sizeof(UINT8),WIMAXRADIO_FWV_LEAF_SIZE},
		{OMA_DM_ST_WIMAXRADIO_MODULE_HW_V,OFFSET_TO_FIELD(ST_WIMAXRadioModule,HwV),1,sizeof(UINT8),WIMAXRADIO_HWV_LEAF_SIZE},
		{OMA_DM_ST_WIMAXRADIO_MODULE_SW_V,OFFSET_TO_FIELD(ST_WIMAXRadioModule,SwV),1,sizeof(UINT8),WIMAXRADIO_SWV_LEAF_SIZE},
		{OMA_DM_ST_WIMAXRADIO_MODULE_MACADDRESS,OFFSET_TO_FIELD(ST_WIMAXRadioModule,MACAddress),1,sizeof(UINT8),WIMAXRADIO_MACADDR_LEAF_SIZE},
		{OMA_DM_ST_WIMAXRADIO_MODULE_SPLOCK,OFFSET_TO_FIELD(ST_WIMAXRadioModule,SPLock),0,sizeof(ST_SPLock),0},
		{OMA_DM_ST_WIMAXRADIO_MODULE_TO_FUMO_REF,OFFSET_TO_FIELD(ST_WIMAXRadioModule,TO_FUMO_REF),1,sizeof(UINT8),WIMAXRADIO_TO_FUMO_REF_LEAF_SIZE},
	},


/*size details for structure ST_SPLock */
	{
		{OMA_DM_ST_SPLOCK_LOCK_STATUS,OFFSET_TO_FIELD(ST_SPLock,LockStatus),0,sizeof(UINT32),0},
		{OMA_DM_ST_SPLOCK_OPERATOR,OFFSET_TO_FIELD(ST_SPLock,Operator),1,sizeof(UINT8),SPLOCK_OPERATOR_LEAF_SIZE},
		{OMA_DM_ST_SPLOCK_VER_NBR,OFFSET_TO_FIELD(ST_SPLock,VerNbr),0,sizeof(UINT32),0},
		{OMA_DM_ST_SPLOCK_LOCK,OFFSET_TO_FIELD(ST_SPLock,Lock),1,sizeof(UINT8),SPLOCK_LOCK_LEAF_SIZE},
	},


/*size details for structure ST_TerminalEquipment */
	{
		{OMA_DM_ST_TERMINAL_EQUIPMENT_DEV_ID,OFFSET_TO_FIELD(ST_TerminalEquipment,DevID),1,sizeof(UINT8),TERMINALEQUIPMENT_DEVID_LEAF_SIZE},
		{OMA_DM_ST_TERMINAL_EQUIPMENT_DEV_TYPE,OFFSET_TO_FIELD(ST_TerminalEquipment,DevType),1,sizeof(UINT8),TERMINALEQUIPMENT_DEVTYPE_LEAF_SIZE},
		{OMA_DM_ST_TERMINAL_EQUIPMENT_MAN,OFFSET_TO_FIELD(ST_TerminalEquipment,Man),1,sizeof(UINT8),TERMINALEQUIPMENT_MAN_LEAF_SIZE},
		{OMA_DM_ST_TERMINAL_EQUIPMENT_MOD,OFFSET_TO_FIELD(ST_TerminalEquipment,Mod),1,sizeof(UINT8),TERMINALEQUIPMENT_MOD_LEAF_SIZE},
		{OMA_DM_ST_TERMINAL_EQUIPMENT_FW_V,OFFSET_TO_FIELD(ST_TerminalEquipment,FwV),1,sizeof(UINT8),TERMINALEQUIPMENT_FWV_LEAF_SIZE},
		{OMA_DM_ST_TERMINAL_EQUIPMENT_HW_V,OFFSET_TO_FIELD(ST_TerminalEquipment,HwV),1,sizeof(UINT8),TERMINALEQUIPMENT_HWV_LEAF_SIZE},
		{OMA_DM_ST_TERMINAL_EQUIPMENT_SW_V,OFFSET_TO_FIELD(ST_TerminalEquipment,SwV),1,sizeof(UINT8),TERMINALEQUIPMENT_SWV_LEAF_SIZE},
	},


/*size details for structure ST_DevCap */
	{
		{OMA_DM_ST_DEV_CAP_IPCAP,OFFSET_TO_FIELD(ST_DevCap,IPCap),0,sizeof(ST_IPCap),0},
		{OMA_DM_ST_DEV_CAP_UPDATE_METHODS,OFFSET_TO_FIELD(ST_DevCap,UpdateMethods),0,sizeof(ST_UpdateMethods),0},
	},


/*size details for structure ST_IPCap */
	{
		{OMA_DM_ST_IPCAP_IPV4,OFFSET_TO_FIELD(ST_IPCap,IPV4),0,sizeof(UINT32),0},
		{OMA_DM_ST_IPCAP_IPV6,OFFSET_TO_FIELD(ST_IPCap,IPV6),0,sizeof(UINT32),0},
		{OMA_DM_ST_IPCAP_CMIPV4,OFFSET_TO_FIELD(ST_IPCap,CMIPV4),0,sizeof(UINT32),0},
		{OMA_DM_ST_IPCAP_CMIPV6,OFFSET_TO_FIELD(ST_IPCap,CMIPV6),0,sizeof(UINT32),0},
	},


/*size details for structure ST_UpdateMethods */
	{
		{OMA_DM_ST_UPDATE_METHODS_SERVER_INITIATED,OFFSET_TO_FIELD(ST_UpdateMethods,ServerInitiated),0,sizeof(UINT32),0},
		{OMA_DM_ST_UPDATE_METHODS_CLIENT_INITIATED,OFFSET_TO_FIELD(ST_UpdateMethods,ClientInitiated),0,sizeof(ST_ClientInitiated),0},
	},


/*size details for structure ST_ClientInitiated */
	{
		{OMA_DM_ST_CLIENT_INITIATED_POLLING_SUPPORTED,OFFSET_TO_FIELD(ST_ClientInitiated,PollingSupported),0,sizeof(UINT32),0},
		{OMA_DM_ST_CLIENT_INITIATED_POLLING_INTERVAL,OFFSET_TO_FIELD(ST_ClientInitiated,PollingInterval),0,sizeof(UINT32),0},
	},


/*size details for structure ST_WIMAXSupp */
	{
		{OMA_DM_ST_WIMAXSUPP_OPERATOR,OFFSET_TO_FIELD(ST_WIMAXSupp,Operator),1,sizeof(ST_Operator),WIMAXSUPP_OPERATOR_NUMBER_OF_NODE},
	},


/*size details for structure ST_Operator */
	{
		{OMA_DM_ST_OPERATOR_NETWORK_PARAMETERS,OFFSET_TO_FIELD(ST_Operator,NetworkParameters),0,sizeof(ST_NetworkParameters),0},
		{OMA_DM_ST_OPERATOR_SUBSCRIPTION_PARAMETERS,OFFSET_TO_FIELD(ST_Operator,SubscriptionParameters),0,sizeof(ST_SubscriptionParameters),0},
		{OMA_DM_ST_OPERATOR_ROOT_CA,OFFSET_TO_FIELD(ST_Operator,RootCA),1,sizeof(ST_RootCA),OPERATOR_ROOTCA_NUMBER_OF_NODE},
		{OMA_DM_ST_OPERATOR_CONTACTS,OFFSET_TO_FIELD(ST_Operator,Contacts),1,sizeof(ST_Contacts),OPERATOR_CONTACTS_NUMBER_OF_NODE},
		{OMA_DM_ST_OPERATOR_TO_IP_REF,OFFSET_TO_FIELD(ST_Operator,TO_IP_REF),1,sizeof(UINT8),OPERATOR_TO_IP_REF_LEAF_SIZE},
	},


/*size details for structure ST_NetworkParameters */
	{
		{OMA_DM_ST_NETWORK_PARAMETERS_H_NSP,OFFSET_TO_FIELD(ST_NetworkParameters,H_NSP),1,sizeof(ST_H_NSP),MAX_HNSP_IDS_PER_OPERATOR},
		{OMA_DM_ST_NETWORK_PARAMETERS_CAPL,OFFSET_TO_FIELD(ST_NetworkParameters,CAPL),0,sizeof(ST_CAPL),0},
		{OMA_DM_ST_NETWORK_PARAMETERS_RAPL,OFFSET_TO_FIELD(ST_NetworkParameters,RAPL),0,sizeof(ST_RAPL),0},
		{OMA_DM_ST_NETWORK_PARAMETERS_CHANNEL_PLAN,OFFSET_TO_FIELD(ST_NetworkParameters,ChannelPlan),0,sizeof(ST_ChannelPlan),0},
		{OMA_DM_ST_NETWORK_PARAMETERS_OPERATOR_NAME,OFFSET_TO_FIELD(ST_NetworkParameters,OperatorName),1,sizeof(UINT8),MAX_SIZE_OPERATORNAME},
		{OMA_DM_ST_NETWORK_PARAMETERS_POLLING_INTERVAL,OFFSET_TO_FIELD(ST_NetworkParameters,PollingInterval),0,sizeof(UINT32),0},
	},


/*size details for structure ST_H_NSP */
	{
		{OMA_DM_ST_H_NSP_H_NSP_ID,OFFSET_TO_FIELD(ST_H_NSP,H_NSP_ID),0,sizeof(UINT32),0},
	},


/*size details for structure ST_CAPL */
	{
		{OMA_DM_ST_CAPL_ENTRIES,OFFSET_TO_FIELD(ST_CAPL,Entries),1,sizeof(ST_CAPLEntries),MAX_CAPL_ENTRIES_PER_NSP},
		{OMA_DM_ST_CAPL_ANY,OFFSET_TO_FIELD(ST_CAPL,Any),0,sizeof(UINT32),0},
	},


/*size details for structure ST_CAPLEntries */
	{
		{OMA_DM_ST_CAPLENTRIES_NAP_ID,OFFSET_TO_FIELD(ST_CAPLEntries,NAP_ID),0,sizeof(UINT32),0},
		{OMA_DM_ST_CAPLENTRIES_PRIORITY,OFFSET_TO_FIELD(ST_CAPLEntries,Priority),0,sizeof(UINT32),0},
		{OMA_DM_ST_CAPLENTRIES_CH_PLAN_REF_IDS,OFFSET_TO_FIELD(ST_CAPLEntries,ChPlanRefIds),1,sizeof(ST_ChPlanRefIds),MAX_CHANNEL_PLAN_REF_ID_PER_CAPL},
	},


/*size details for structure ST_ChPlanRefIds */
	{
		{OMA_DM_ST_CH_PLAN_REF_IDS_REF_ID,OFFSET_TO_FIELD(ST_ChPlanRefIds,RefId),1,sizeof(UINT8),CHANNEL_REFID_LEAF_SIZE},
	},


/*size details for structure ST_RAPL */
	{
		{OMA_DM_ST_RAPL_ENTRIES,OFFSET_TO_FIELD(ST_RAPL,Entries),1,sizeof(ST_RAPLEntries),MAX_RAPL_ENTRIES_PER_NSP},
		{OMA_DM_ST_RAPL_ANY,OFFSET_TO_FIELD(ST_RAPL,Any),0,sizeof(UINT32),0},
	},


/*size details for structure ST_RAPLEntries */
	{
		{OMA_DM_ST_RAPLENTRIES_V_NSP_ID,OFFSET_TO_FIELD(ST_RAPLEntries,V_NSP_ID),0,sizeof(UINT32),0},
		{OMA_DM_ST_RAPLENTRIES_PRIORITY,OFFSET_TO_FIELD(ST_RAPLEntries,Priority),0,sizeof(UINT32),0},
	},


/*size details for structure ST_ChannelPlan */
	{
		{OMA_DM_ST_CHANNEL_PLAN_ENTRIES,OFFSET_TO_FIELD(ST_ChannelPlan,Entries),1,sizeof(ST_ChannelPlanEntries),MAX_CHANNEL_PLAN_ENTRIES_PER_NSP},
		{OMA_DM_ST_CHANNEL_PLAN_BW,OFFSET_TO_FIELD(ST_ChannelPlan,BW),0,sizeof(UINT32),0},
		{OMA_DM_ST_CHANNEL_PLAN_FFTSIZE,OFFSET_TO_FIELD(ST_ChannelPlan,FFTSize),0,sizeof(UINT32),0},
		{OMA_DM_ST_CHANNEL_PLAN_DUPLEX_MODE,OFFSET_TO_FIELD(ST_ChannelPlan,DuplexMode),0,sizeof(UINT32),0},
	},


/*size details for structure ST_ChannelPlanEntries */
	{
		{OMA_DM_ST_CHANNEL_PLAN_ENTRIES_ID,OFFSET_TO_FIELD(ST_ChannelPlanEntries,Id),1,sizeof(UINT8),CHANNEL_REFID_LEAF_SIZE},
		{OMA_DM_ST_CHANNEL_PLAN_ENTRIES_FIRST_FREQ,OFFSET_TO_FIELD(ST_ChannelPlanEntries,FirstFreq),0,sizeof(UINT32),0},
		{OMA_DM_ST_CHANNEL_PLAN_ENTRIES_LAST_FREQ,OFFSET_TO_FIELD(ST_ChannelPlanEntries,LastFreq),0,sizeof(UINT32),0},
		{OMA_DM_ST_CHANNEL_PLAN_ENTRIES_NEXT_FREQ_STEP,OFFSET_TO_FIELD(ST_ChannelPlanEntries,NextFreqStep),0,sizeof(UINT32),0},
		{OMA_DM_ST_CHANNEL_PLAN_ENTRIES_PREAMBLES,OFFSET_TO_FIELD(ST_ChannelPlanEntries,Preambles),1,sizeof(UINT8),CHANNEL_PLAN_PREAMBLE_LEAF_SIZE},
		{OMA_DM_ST_CHANNEL_PLAN_ENTRIES_BW,OFFSET_TO_FIELD(ST_ChannelPlanEntries,BW),0,sizeof(UINT32),0},
		{OMA_DM_ST_CHANNEL_PLAN_ENTRIES_FFTSIZE,OFFSET_TO_FIELD(ST_ChannelPlanEntries,FFTSize),0,sizeof(UINT32),0},
		{OMA_DM_ST_CHANNEL_PLAN_ENTRIES_DUPLEX_MODE,OFFSET_TO_FIELD(ST_ChannelPlanEntries,DuplexMode),0,sizeof(UINT32),0},
	},


/*size details for structure ST_SubscriptionParameters */
	{
		{OMA_DM_ST_SUBSCRIPTION_PARAMETERS_PRIMARY,OFFSET_TO_FIELD(ST_SubscriptionParameters,Primary),0,sizeof(ST_Primary),0},
		{OMA_DM_ST_SUBSCRIPTION_PARAMETERS_OTHER_SUBSCRIPTIONS,OFFSET_TO_FIELD(ST_SubscriptionParameters,OtherSubscriptions),1,sizeof(ST_OtherSubscriptions),SUBSCRIPTIONPARAMETERS_OTHERSUBSCRIPTIONS_NUMBER_OF_NODES},
	},


/*size details for structure ST_Primary */
	{
		{OMA_DM_ST_PRIMARY_NAME,OFFSET_TO_FIELD(ST_Primary,Name),1,sizeof(UINT8),PRIMARY_NAME_LEAF_SIZE},
		{OMA_DM_ST_PRIMARY_ACTIVATED,OFFSET_TO_FIELD(ST_Primary,Activated),0,sizeof(UINT32),0},
		{OMA_DM_ST_PRIMARY_EAP,OFFSET_TO_FIELD(ST_Primary,EAP),1,sizeof(ST_EAP),PRIMARY_EAP_NUMBER_OF_NODE},
	},


/*size details for structure ST_EAP */
	{
		{OMA_DM_ST_EAP_METHOD_TYPE,OFFSET_TO_FIELD(ST_EAP,METHOD_TYPE),0,sizeof(UINT32),0},
		{OMA_DM_ST_EAP_VENDOR_ID,OFFSET_TO_FIELD(ST_EAP,VENDOR_ID),0,sizeof(UINT32),0},
		{OMA_DM_ST_EAP_VENDOR_TYPE,OFFSET_TO_FIELD(ST_EAP,VENDOR_TYPE),0,sizeof(UINT32),0},
		{OMA_DM_ST_EAP_USER_IDENTITY,OFFSET_TO_FIELD(ST_EAP,UserIdentity),1,sizeof(UINT8),EAP_USERIDENTITY_LEAF_SIZE},
		{OMA_DM_ST_EAP_PROVISIONED_PSEUDO_IDENTITY,OFFSET_TO_FIELD(ST_EAP,PROVISIONED_PSEUDO_IDENTITY),1,sizeof(UINT8),EAP_PROVISIONED_PSEUDO_IDENTITY_LEAF_SIZE},
		{OMA_DM_ST_EAP_PASSWORD,OFFSET_TO_FIELD(ST_EAP,PASSWORD),1,sizeof(UINT8),EAP_PASSWORD_LEAF_SIZE},
		{OMA_DM_ST_EAP_REALM,OFFSET_TO_FIELD(ST_EAP,REALM),1,sizeof(UINT8),EAP_REALM_LEAF_SIZE},
		{OMA_DM_ST_EAP_USE_PRIVACY,OFFSET_TO_FIELD(ST_EAP,USE_PRIVACY),0,sizeof(UINT8),0},
		{OMA_DM_ST_EAP_ENCAPS,OFFSET_TO_FIELD(ST_EAP,ENCAPS),0,sizeof(UINT32),0},
		{OMA_DM_ST_EAP_VFY_SERVER_REALM,OFFSET_TO_FIELD(ST_EAP,VFY_SERVER_REALM),0,sizeof(UINT32),0},
		{OMA_DM_ST_EAP_SERVER_REALMS,OFFSET_TO_FIELD(ST_EAP,SERVER_REALMS),1,sizeof(ST_SERVER_REALMS),EAP_SERVER_REALMS_NUMBER_OF_NODE},
		{OMA_DM_ST_EAP_EAP_AKA,OFFSET_TO_FIELD(ST_EAP,EAP_AKA),0,sizeof(ST_EAP_AKA),0},
		{OMA_DM_ST_EAP_CERT,OFFSET_TO_FIELD(ST_EAP,CERT),1,sizeof(ST_CERT),EAP_CERT_NUMBER_OF_NODE},
	},


/*size details for structure ST_SERVER_REALMS */
	{
		{OMA_DM_ST_SERVER_REALMS_SERVER_REALM,OFFSET_TO_FIELD(ST_SERVER_REALMS,SERVER_REALM),1,sizeof(UINT8),SERVER_REALM_LEAF_SIZE},
	},


/*size details for structure ST_EAP_AKA */
	{
		{OMA_DM_ST_EAP_AKA_USE_CHECK_CODE,OFFSET_TO_FIELD(ST_EAP_AKA,USE_CHECK_CODE),0,sizeof(UINT32),0},
	},


/*size details for structure ST_CERT */
	{
		{OMA_DM_ST_CERT_CERT_TYPE,OFFSET_TO_FIELD(ST_CERT,CERT_TYPE),1,sizeof(UINT8),CERT_CERT_TYPE_LEAF_SIZE},
		{OMA_DM_ST_CERT_SER_NUM,OFFSET_TO_FIELD(ST_CERT,SER_NUM),0,sizeof(UINT32),0},
		{OMA_DM_ST_CERT_THUMBPRINT,OFFSET_TO_FIELD(ST_CERT,THUMBPRINT),0,sizeof(UINT32),0},
	},


/*size details for structure ST_OtherSubscriptions */
	{
		{OMA_DM_ST_OTHER_SUBSCRIPTIONS_NAME,OFFSET_TO_FIELD(ST_OtherSubscriptions,Name),1,sizeof(UINT8),OTHERSUBSCRIPTIONS_NAME_LEAF_SIZE},
		{OMA_DM_ST_OTHER_SUBSCRIPTIONS_ACTIVATED,OFFSET_TO_FIELD(ST_OtherSubscriptions,Activated),0,sizeof(UINT32),0},
		{OMA_DM_ST_OTHER_SUBSCRIPTIONS_EAP,OFFSET_TO_FIELD(ST_OtherSubscriptions,EAP),1,sizeof(ST_EAP),OTHERSUBSCRIPTIONS_EAP_NUMBER_OF_NODE},
	},


/*size details for structure ST_RootCA */
	{
		{OMA_DM_ST_ROOT_CA_CERT_ID,OFFSET_TO_FIELD(ST_RootCA,CertID),1,sizeof(UINT8),ROOTCA_CERTID_LEAF_SIZE},
		{OMA_DM_ST_ROOT_CA_SIGNATURE,OFFSET_TO_FIELD(ST_RootCA,Signature),1,sizeof(UINT8),ROOTCA_SIGNATURE_LEAF_SIZE},
		{OMA_DM_ST_ROOT_CA_CERTIFICATE,OFFSET_TO_FIELD(ST_RootCA,Certificate),1,sizeof(UINT8),ROOTCA_CERTIFICATE_LEAF_SIZE},
	},


/*size details for structure ST_Contacts */
	{
		{OMA_DM_ST_CONTACTS_TYPE,OFFSET_TO_FIELD(ST_Contacts,Type),0,sizeof(UINT32),0},
		{OMA_DM_ST_CONTACTS_TRIGGER,OFFSET_TO_FIELD(ST_Contacts,Trigger),1,sizeof(UINT8),CONTACTS_TRIGGER_LEAF_SIZE},
		{OMA_DM_ST_CONTACTS_URI,OFFSET_TO_FIELD(ST_Contacts,URI),1,sizeof(UINT8),CONTACTS_URI_LEAF_SIZE},
		{OMA_DM_ST_CONTACTS_TEXT,OFFSET_TO_FIELD(ST_Contacts,Text),1,sizeof(UINT8),CONTACTS_TEXT_LEAF_SIZE},
	},


/*size details for structure ST_IP */
	{
		{OMA_DM_ST_IP_IPV4,OFFSET_TO_FIELD(ST_IP,IPV4),0,sizeof(ST_IPV4),0},
		{OMA_DM_ST_IP_IPV6,OFFSET_TO_FIELD(ST_IP,IPV6),0,sizeof(ST_IPV6),0},
		{OMA_DM_ST_IP_MIPV4,OFFSET_TO_FIELD(ST_IP,MIPv4),0,sizeof(ST_MIPv4),0},
		{OMA_DM_ST_IP_MIPV6,OFFSET_TO_FIELD(ST_IP,MIPv6),0,sizeof(ST_MIPv6),0},
	},


/*size details for structure ST_IPV4 */
	{
		{OMA_DM_ST_IPV4_AUTOCONFIG,OFFSET_TO_FIELD(ST_IPV4,Autoconfig),0,sizeof(UINT32),0},
		{OMA_DM_ST_IPV4_IPADDR,OFFSET_TO_FIELD(ST_IPV4,IPAddr),1,sizeof(UINT8),IPV4_IPADDR_LEAF_SIZE},
		{OMA_DM_ST_IPV4_NET_MASK,OFFSET_TO_FIELD(ST_IPV4,NetMask),1,sizeof(UINT8),IPV4_NETMASK_LEAF_SIZE},
		{OMA_DM_ST_IPV4_GATEWAY,OFFSET_TO_FIELD(ST_IPV4,Gateway),1,sizeof(UINT8),IPV4_GATEWAY_LEAF_SIZE},
		{OMA_DM_ST_IPV4_AUTO_DNS,OFFSET_TO_FIELD(ST_IPV4,AutoDNS),0,sizeof(UINT32),0},
	},


/*size details for structure ST_IPV6 */
	{
		{OMA_DM_ST_IPV6_AUTOCONFIG,OFFSET_TO_FIELD(ST_IPV6,Autoconfig),0,sizeof(UINT32),0},
		{OMA_DM_ST_IPV6_IPADDR,OFFSET_TO_FIELD(ST_IPV6,IPAddr),1,sizeof(UINT8),IPV6_IPADDR_LEAF_SIZE},
		{OMA_DM_ST_IPV6_NET_MASK,OFFSET_TO_FIELD(ST_IPV6,NetMask),1,sizeof(UINT8),IPV6_NETMASK_LEAF_SIZE},
		{OMA_DM_ST_IPV6_GATEWAY,OFFSET_TO_FIELD(ST_IPV6,Gateway),1,sizeof(UINT8),IPV6_GATEWAY_LEAF_SIZE},
		{OMA_DM_ST_IPV6_AUTO_DNS,OFFSET_TO_FIELD(ST_IPV6,AutoDNS),0,sizeof(UINT32),0},
	},


/*size details for structure ST_MIPv4 */
	{
		{OMA_DM_ST_MIPV4_SHARED_SECRET,OFFSET_TO_FIELD(ST_MIPv4,SharedSecret),0,sizeof(ST_SharedSecret),0},
		{OMA_DM_ST_MIPV4_PROTOCOL,OFFSET_TO_FIELD(ST_MIPv4,Protocol),0,sizeof(ST_Protocolv4),0},
	},


/*size details for structure ST_SharedSecret */
	{
		{OMA_DM_ST_SHARED_SECRET_NAI,OFFSET_TO_FIELD(ST_SharedSecret,NAI),1,sizeof(ST_NAI),SHAREDSECRET_NAI_NUMBER_OF_NODE},
	},


/*size details for structure ST_NAI */
	{
		{OMA_DM_ST_NAI_USERNAME,OFFSET_TO_FIELD(ST_NAI,Username),1,sizeof(UINT8),NAI_USERNAME_LEAF_SIZE},
		{OMA_DM_ST_NAI_REALM,OFFSET_TO_FIELD(ST_NAI,Realm),1,sizeof(UINT8),NAI_REALM_LEAF_SIZE},
		{OMA_DM_ST_NAI_USE_PSEUDO,OFFSET_TO_FIELD(ST_NAI,UsePseudo),0,sizeof(UINT32),0},
	},


/*size details for structure ST_Protocolv4 */
	{
		{OMA_DM_ST_PROTOCOLV4_REV_TUN,OFFSET_TO_FIELD(ST_Protocolv4,RevTun),0,sizeof(UINT32),0},
		{OMA_DM_ST_PROTOCOLV4_RETRY_COUNT,OFFSET_TO_FIELD(ST_Protocolv4,RetryCount),0,sizeof(UINT32),0},
		{OMA_DM_ST_PROTOCOLV4_RETRY_TIMER,OFFSET_TO_FIELD(ST_Protocolv4,RetryTimer),0,sizeof(UINT32),0},
		{OMA_DM_ST_PROTOCOLV4_REG_PERIOD_REL,OFFSET_TO_FIELD(ST_Protocolv4,RegPeriodRel),0,sizeof(UINT32),0},
		{OMA_DM_ST_PROTOCOLV4_REG_PERIOD,OFFSET_TO_FIELD(ST_Protocolv4,RegPeriod),0,sizeof(UINT32),0},
		{OMA_DM_ST_PROTOCOLV4_NAT_TRAVERSAL,OFFSET_TO_FIELD(ST_Protocolv4,NatTraversal),1,sizeof(UINT8),PROTOCOL_NATRAVERSAL_LEAF_SIZE},
	},


/*size details for structure ST_MIPv6 */
	{
		{OMA_DM_ST_MIPV6_SHARED_SECRET,OFFSET_TO_FIELD(ST_MIPv6,SharedSecret),0,sizeof(ST_SharedSecret),0},
		{OMA_DM_ST_MIPV6_PROTOCOL,OFFSET_TO_FIELD(ST_MIPv6,Protocol),0,sizeof(ST_Protocolv6),0},
	},


/*size details for structure ST_Protocolv6 */
	{
		{OMA_DM_ST_PROTOCOLV6_ROUTE_OPT,OFFSET_TO_FIELD(ST_Protocolv6,RouteOpt),0,sizeof(UINT32),0},
		{OMA_DM_ST_PROTOCOLV6_RETRY_COUNT,OFFSET_TO_FIELD(ST_Protocolv6,RetryCount),0,sizeof(UINT32),0},
		{OMA_DM_ST_PROTOCOLV6_RETRY_TIMER,OFFSET_TO_FIELD(ST_Protocolv6,RetryTimer),0,sizeof(UINT32),0},
		{OMA_DM_ST_PROTOCOLV6_BINDING_LIFE_TIME_REL,OFFSET_TO_FIELD(ST_Protocolv6,BindingLifeTimeRel),0,sizeof(UINT32),0},
		{OMA_DM_ST_PROTOCOLV6_BINDING_LIFE_TIME,OFFSET_TO_FIELD(ST_Protocolv6,BindingLifeTime),0,sizeof(UINT32),0},
		{OMA_DM_ST_PROTOCOLV6_SIGNALING_PROTECTION,OFFSET_TO_FIELD(ST_Protocolv6,SignalingProtection),0,sizeof(UINT8),0},
	},


/*size details for structure ST_Apps */
	{
		{OMA_DM_ST_APPS_PUI,OFFSET_TO_FIELD(ST_Apps,PUI),1,sizeof(UINT8),APPS_PUI_LEAF_SIZE},
		{OMA_DM_ST_APPS_PRI,OFFSET_TO_FIELD(ST_Apps,PRI),1,sizeof(UINT8),APPS_PRI_LEAF_SIZE},
		{OMA_DM_ST_APPS_SIP_PASSWORD,OFFSET_TO_FIELD(ST_Apps,SIP_Password),1,sizeof(UINT8),APPS_SIP_PASSWORD_LEAF_SIZE},
		{OMA_DM_ST_APPS_HOME_DOMAIN,OFFSET_TO_FIELD(ST_Apps,Home_Domain),1,sizeof(UINT8),APPS_HOME_DOMAIN_LEAF_SIZE},
		{OMA_DM_ST_APPS_SIP_PROXY_SERVER,OFFSET_TO_FIELD(ST_Apps,SIP_Proxy_Server),1,sizeof(UINT8),APPS_SIP_PROXY_SERVER_LEAF_SIZE},
		{OMA_DM_ST_APPS_CONFERENCE_URI,OFFSET_TO_FIELD(ST_Apps,Conference_URI),1,sizeof(UINT8),APPS_CONFERENCE_URI_LEAF_SIZE},
		{OMA_DM_ST_APPS_VO_IP_ACTIVATION,OFFSET_TO_FIELD(ST_Apps,VoIP_Activation),0,sizeof(UINT32),0},
		{OMA_DM_ST_APPS_T1,OFFSET_TO_FIELD(ST_Apps,T1),0,sizeof(UINT32),0},
		{OMA_DM_ST_APPS_T2,OFFSET_TO_FIELD(ST_Apps,T2),0,sizeof(UINT32),0},
		{OMA_DM_ST_APPS_T4,OFFSET_TO_FIELD(ST_Apps,T4),0,sizeof(UINT32),0},
		{OMA_DM_ST_APPS_REG_REFRESH_INTVL,OFFSET_TO_FIELD(ST_Apps,REG_Refresh_Intvl),0,sizeof(UINT32),0},
		{OMA_DM_ST_APPS_SESSION_REFRESH_INTVL,OFFSET_TO_FIELD(ST_Apps,Session_Refresh_Intvl),0,sizeof(UINT32),0},
	},


/*size details for structure ST_FUMO */
	{
		{OMA_DM_ST_FUMO_PKG_NAME,OFFSET_TO_FIELD(ST_FUMO,PkgName),1,sizeof(UINT8),FUMO_PKGNAME_LEAF_SIZE},
		{OMA_DM_ST_FUMO_PKG_VERSION,OFFSET_TO_FIELD(ST_FUMO,PkgVersion),1,sizeof(UINT8),FUMO_PKGVERSION_LEAF_SIZE},
		{OMA_DM_ST_FUMO_UPDATE,OFFSET_TO_FIELD(ST_FUMO,Update),0,sizeof(ST_Update),0},
		{OMA_DM_ST_FUMO_DOWNLOAD,OFFSET_TO_FIELD(ST_FUMO,Download),0,sizeof(ST_Download),0},
		{OMA_DM_ST_FUMO_DOWNLOAD_AND_UPDATE,OFFSET_TO_FIELD(ST_FUMO,DownloadAndUpdate),0,sizeof(ST_DownloadAndUpdate),0},
		{OMA_DM_ST_FUMO_STATE,OFFSET_TO_FIELD(ST_FUMO,State),0,sizeof(UINT32),0},
	},


/*size details for structure ST_Update */
	{
		{OMA_DM_ST_UPDATE_PKG_DATA,OFFSET_TO_FIELD(ST_Update,PkgData),1,sizeof(UINT8),UPDATE_PKGDATA_LEAF_SIZE},
	},


/*size details for structure ST_Download */
	{
		{OMA_DM_ST_DOWNLOAD_PKG_URL,OFFSET_TO_FIELD(ST_Download,PkgURL),1,sizeof(UINT8),DOWNLOAD_PKGURL_LEAF_SIZE},
	},


/*size details for structure ST_DownloadAndUpdate */
	{
		{OMA_DM_ST_DOWNLOAD_AND_UPDATE_PKG_URL,OFFSET_TO_FIELD(ST_DownloadAndUpdate,PkgURL),1,sizeof(UINT8),DOWNLOADANDUPDATE_PKGURL_LEAF_SIZE},
	},


/*size details for structure ST_MRU_TABLE */
	{
		{OMA_DM_ST_MRU_TABLE_UCH_MRUDATA,OFFSET_TO_FIELD(ST_MRU_TABLE,uchMRUData),1,sizeof(UINT8),MRU_TABLE_LEAF_SIZE},
	},
};
